### PR TITLE
Add access file for Pablo Galindo

### PR DESCRIPTION
**Pull request by pablogsal**
Grant access on buildbot master.

### CODE REVIEW

**Comment by pablogsal** [comment]
CC: @zware

**Comment by zware** [comment]
@ewdurbin Can we grant Pablo access to buildbot.python.org please?  He's our main buildbot watcher these days, and would like to get more involved with its administration.

**Comment by ewdurbin** [comment]
Certainly, opening a Pull Request adding themself is most direct. Otherwise
I’ll follow up with what’s needed in the morning (Eastern timezone)

**Comment by zware** [comment]
@ewdurbin This is that PR :)

**Comment by ewdurbin** [comment]
Githubbin’ from phones is dangerous. Gimme 10 minutes.


On September 11, 2018 at 9:03:42 PM, Zachary Ware (notifications@github.com)
wrote:

@ewdurbin <https://github.com/ewdurbin> This is that PR :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/python/psf-chef/pull/166#issuecomment-420476396>, or mute
the thread

**Comment by zware** [comment]
No problem.  I only just realized that it's 21:00 over there.  Thanks for the quick response!

**Comment by ewdurbin** [comment]
_should_ be all set! if not, please let me know @pablogsal!

**Pull request merged**
