### PR TITLE
Removes local_settings template and config for pycon:

### PR DESCRIPTION
**Pull request by calebsmith**
This template and associated settings file aren't needed as the
production or staging settings files are used by manage.py from the
IS_PRODUCTION environment variable set in the environment elsewhere in
the recipe. Having this in place only leads to confusion.

Refers to https://github.com/PyCon/pycon/issues/377

Also, just realizing I should probably remove the settings: bit from the django do entirely but unsure enough of how Chef uses these bits that I could use some guidance there. I was able to confirm on staging that the staging settings file was in fact being used and local_settings ignored.

### CODE REVIEW

**Comment by ewdurbin** [comment]
@calebsmith thanks, i did the base work for moving this to our new infrastructure, and the psf-salt environment over the weekend.

it should be all set with a few more evenings of work, so there's no real worry to modify this chef cookbook unless it's blocking work for the team.

**Comment by calebsmith** [comment]
ok, no problem. Was sort of finishing up from where I left off before a vacation. If that is in the works, we can close. This is sort of a "cleanup" task and not really blocking anything.

**Comment by ewdurbin** [comment]
[here](https://github.com/python/psf-salt/compare/ff08a267d20defeb8a947987e8b4eea42cb7d295...e71251ce6f7b6afbff378985c8670d949392a3a9) is said work, @calebsmith 

it covers a lot of your previous notes (up to date distro, no more running as root, etc) :)

**Comment by calebsmith** [comment]
Ok, thanks @ewdurbin

**Pull request closed without merging**
