### PR TITLE
add haypo to sudoers on python-speed

### PR DESCRIPTION
**Pull request by ewdurbin**

### CODE REVIEW

**Comment by haypo** [comment]
@fijal : Hey, would you mind to review this change? Thanks.

**Comment by MarkMangoba** [comment]
@fijal just checking if you had a chance to review this.

**Comment by haypo** [comment]
I upgraded Ubuntu since 14.04 to 16.06 on speed-python.osuosl.org. I was root before. Now I'm unable to use the server to run benchmarks, and so speed.python.org is not more updated.

Is there a reason to not trust me?

This issue becomes annoying, benchmarks are important for my work, and we waste an idle server at the PSF...

**Comment by ewdurbin** [comment]
@haypo went and logged into the box, found a backup of a previous group file adding your user to the admin group. will merge this and roll it out now.

**Comment by haypo** [comment]
Thank you!

**Comment by haypo** [comment]
It works, I'm able to run commands as root without having to type a password (I have no password).

**Pull request merged**
