### PR TITLE
Access to the code speed

### PR DESCRIPTION
**Pull request by planrich**
I need access to the code speed machine to fix the problems with the comparison

### CODE REVIEW

**Comment by planrich** [comment]
Any updates?
@fijal can you push this forward?

**Comment by haypo** [comment]
> I need access to the code speed machine to fix the problems with the comparison

Which machine? I'm using speed-python.osuosl.org to run CPython benchmarks, and speed-web.iad1.psf.io for the Codespeed instance of speed.python.org.

**Comment by haypo** [comment]
Oh, this is a pull request, not an issue :-) I see "pypy-codespeed" in the change, ok.

**Comment by ewdurbin** [comment]
oh hi! dropping by this repo for the first time in a while. is this still desired?

**Comment by ewdurbin** [comment]
If this is still desired, a PR adding a key to the repo that now manages the code speed similar to https://github.com/python/psf-salt/blob/96fe18fa0e10bfa36c274ac4983b5236f7c0c1f0/pillar/base/users.sls#L221-L228 should be opened.

**Pull request closed without merging**
